-- =========================================================
-- Creazione tabella Province
-- =========================================================
CREATE TABLE Province
(
    Sigla NVARCHAR(2) NOT NULL PRIMARY KEY,
    Nome  NVARCHAR(50) NOT NULL
);

-- =========================================================
-- Inserimento province italiane (ordinate per Nome)
-- =========================================================
INSERT INTO Province (Sigla, Nome) VALUES
('AG',N'Agrigento'),
('AL',N'Alessandria'),
('AN',N'Ancona'),
('AO',N'Aosta'),
('AR',N'Arezzo'),
('AP',N'Ascoli Piceno'),
('AT',N'Asti'),
('AV',N'Avellino'),
('BA',N'Bari'),
('BT',N'Barletta-Andria-Trani'),
('BL',N'Belluno'),
('BN',N'Benevento'),
('BG',N'Bergamo'),
('BI',N'Biella'),
('BO',N'Bologna'),
('BZ',N'Bolzano'),
('BS',N'Brescia'),
('BR',N'Brindisi'),
('CA',N'Cagliari'),
('CL',N'Caltanissetta'),
('CB',N'Campobasso'),
('CE',N'Caserta'),
('CT',N'Catania'),
('CZ',N'Catanzaro'),
('CH',N'Chieti'),
('CO',N'Como'),
('CS',N'Cosenza'),
('CR',N'Cremona'),
('KR',N'Crotone'),
('CN',N'Cuneo'),
('EN',N'Enna'),
('FM',N'Fermo'),
('FE',N'Ferrara'),
('FI',N'Firenze'),
('FG',N'Foggia'),
('FC',N'Forlì-Cesena'),
('FR',N'Frosinone'),
('GE',N'Genova'),
('GO',N'Gorizia'),
('GR',N'Grosseto'),
('IM',N'Imperia'),
('IS',N'Isernia'),
('SP',N'La Spezia'),
('AQ',N'L''Aquila'),
('LT',N'Latina'),
('LE',N'Lecce'),
('LC',N'Lecco'),
('LI',N'Livorno'),
('LO',N'Lodi'),
('LU',N'Lucca'),
('MC',N'Macerata'),
('MN',N'Mantova'),
('MS',N'Massa-Carrara'),
('MT',N'Matera'),
('ME',N'Messina'),
('MI',N'Milano'),
('MO',N'Modena'),
('MB',N'Monza e Brianza'),
('NA',N'Napoli'),
('NO',N'Novara'),
('NU',N'Nuoro'),
('OR',N'Oristano'),
('PD',N'Padova'),
('PA',N'Palermo'),
('PR',N'Parma'),
('PV',N'Pavia'),
('PG',N'Perugia'),
('PU',N'Pesaro e Urbino'),
('PE',N'Pescara'),
('PC',N'Piacenza'),
('PI',N'Pisa'),
('PT',N'Pistoia'),
('PN',N'Pordenone'),
('PZ',N'Potenza'),
('PO',N'Prato'),
('RG',N'Ragusa'),
('RA',N'Ravenna'),
('RC',N'Reggio Calabria'),
('RE',N'Reggio Emilia'),
('RI',N'Rieti'),
('RN',N'Rimini'),
('RM',N'Roma'),
('RO',N'Rovigo'),
('SA',N'Salerno'),
('SS',N'Sassari'),
('SV',N'Savona'),
('SI',N'Siena'),
('SR',N'Siracusa'),
('SO',N'Sondrio'),
('SU',N'Sud Sardegna'),
('TA',N'Taranto'),
('TE',N'Teramo'),
('TR',N'Terni'),
('TO',N'Torino'),
('TP',N'Trapani'),
('TN',N'Trento'),
('TV',N'Treviso'),
('TS',N'Trieste'),
('UD',N'Udine'),
('VA',N'Varese'),
('VE',N'Venezia'),
('VB',N'Verbano-Cusio-Ossola'),
('VC',N'Vercelli'),
('VR',N'Verona'),
('VV',N'Vibo Valentia'),
('VI',N'Vicenza'),
('VT',N'Viterbo');

-- =========================================================
-- Vincolo di chiave esterna su Utenti.Provincia
-- =========================================================
ALTER TABLE Utenti
ADD CONSTRAINT FK_Utenti_Province
FOREIGN KEY (Provincia)
REFERENCES Province(Sigla);
